### ISSUE TITLE
Working example?

### ISSUE THREAD

**Issue by jcmontx** [grumar/adal-angular5#11]
I've been trying to use the library with no success. A working example would be fantastic.

**Comment by grumar** [comment]
It is working example. Please create a plunker or attach Your code.

**Comment by jcmontx** [comment]
I mean, a client angular 5 app using the library

**Comment by nybroe** [comment]
Definitely - bumping up the adal-angular4 example to use this version aint that easy - I am on my 2nd hour of creating this "simple" example and I keep running into different issues.
A working example without needing to bump up from an earlier example would be great!

**Comment by jcmontx** [comment]
I finally got this to work. [Here's](https://github.com/jcmontx/angular5-adal-example) a full example 😄.  Remember to put your tenant and clientId. 

Feel free to add it to the docs.

**Comment by ringodotnl** [comment]
Thx jcmontx, a full example with aquiretoken would be nice, you have any Grumar ?

I my currently example when you login the first time it seems to load the example app like 3 times when uising aquiretoken to the app, after login at the AD.

Might be due a issue at handleWindowCallback not sure.

Cheers.

**Comment by nybroe** [comment]
So a couple of questions:

**1)** 
I have also tried to add the use of acquireToken in @jcmontx 's example and was able to retrieve the access_token (not the id_token).
I might be misunderstanding the use of adal.js but in order to get the actual access_token and thereby getting the appRoles (which is not included in the id_token), I need to login in first - getting the id_token and then afterwards getting the access_token using acquireToken?
Is there a way to retrieve the access_token without having to log in?

**2)**
My flow currently looks like this:
1) Initial login using "login()"
2) retrieving access_token using acquireToken() by setting the resource parameter to the application resourceURI and not the clientId. Using the clientId as the resource parameter just retrieves the id_token from the cache.

The only drawback using the flow above is that the state upon callback is not the same as the expected state and the state is set to false, given an errormessage. When the state is not valid the handleWindowCallback() fails to update the sessionCache and the access_token in the cache remains the same as the id_token... For now I am not using handleWindowCallback and manually updating the sessionCache but I would like to avoid any manual "hacks".

Am I using it wrong or is this a bug?

**Comment by AlexeyBoiko** [comment]
Thank you for the library. @jcmontx example is useful, but did not show to use token.

I can successfully get userInfo after login (it is shown in [example](https://github.com/jcmontx/angular5-adal-example/blob/master/src/app/app.component.ts)). But when I try to call Microsoft Graph API I get not authorized exception.

Could you please provide a full example with calling Microsoft Graph API or other Office 365 API.

Here is my [example](https://github.com/AlexeyBoiko/angular5-office365-adal-example) of  using Microsoft Graph API, without adal-angular5. There [@types/adal](https://www.npmjs.com/package/@types/adal) is used.

**Comment by pvsherman** [comment]
@jcmontx  Example works fine, but when I try to move code into my project I run into issue where 
import { adal } from 'adal-angular'; gives me an error:
_Could not find a declaration file for module 'adal-angular'. '..../node_modules/adal-angular/lib/adal.js' implicitly has 'any' type. Try 'npm install `@types/adal-angular`'  if it exists or add a new declaration (.d.ts) file containing declare module 'adal-angular'_

I tried to "npm install " but it didn't help.
I can't see a difference between two projects. Where should I look?

**Comment by grumar** [comment]
Thank You @jcmontx I copied Your example.
